version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: aml
      MYSQL_USER: user
      MYSQL_PASSWORD: password # Это для создания дополнительного пользователя, не root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Если у вас есть скрипт инициализации
  app:
    image: blacksweetik/aml_bot:amd64
    build: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: aml
    ports:
      - "8000:8000"

volumes:
  db_data:
